#!/usr/bin/env bash
#transfers a file from our client to a server:
#Accepts 4 parameters
#The path to the file to be transferred
#The IP of the server we want to transfer the file to
#The username scp connects with
#The path to the SSH private key that scp uses

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assigning Arguments to variables

path_tofile=$1
ip_number=$2
username=$3
ssh_keypath=$4

# Disabbling strict Host Key checking

scp -o "StrictHostKeyChecking no" -i "$ssh_keypath" "$path_tofile" "$username@$ip_number:~/"

# Checking if the transfer was successful
if [ $? -eq 0 ]
then
  echo "FILE TRANSFER WAS SUCCESSFULL"
else
  echo "FILE TRANSFER FAILED"
fi
