#!/usr/bin/env bash
# Use an until loop to display "Best School" 10 times

# Initialize a counter
counter=0

until [ $counter -ge 10 ]
do
    echo "Best School"
    
    # Increment the counter
    ((counter++))
done
