#!/usr/bin/env bash
# a Bash script that displays Best School 10 times

#Initialize counter
counter=1

while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]
	then 
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi

	#increment counter
	((counter++))
done
